# Generated by Django 4.2.6 on 2023-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('lost_luggages', 'Lost Luggages'), ('lost_tickets', 'Lost Tickets'), ('lost_profile', 'Lost Profile')], max_length=255)),
                ('department', models.CharField(choices=[('baggage_luggages', 'Baggage & Luggages'), ('support_tickets', 'Support Tickets'), ('baggage_luggages', 'Baggage & Luggages')], max_length=255)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('difficult', 'Difficult')], max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
