# Generated by Django 4.2.6 on 2023-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_reportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upazila',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
