# Generated by Django 4.2.6 on 2023-11-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_district_profile_dividion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dividion',
            new_name='division',
        ),
    ]
