# Generated by Django 4.2.6 on 2023-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='fire',
        ),
        migrations.AddField(
            model_name='property',
            name='fire_extinction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='bachelor_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('0-10', '0 to 10'), ('11-20', '11 to 20'), ('20+', '20 up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='cctv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='electricity',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='family_member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='flat_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas',
            field=models.CharField(choices=[('lpg', 'LPG'), ('supply_gas', 'Supply Gas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='generator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hostel_plan',
            field=models.FileField(blank=True, null=True, upload_to='hostel_plans/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hostel_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hostel_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lift',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_for',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='office_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('apartment', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(choices=[('family', 'Family'), ('sublet', 'Sublet'), ('bachelor', 'Bachelor'), ('hostel', 'Hostel'), ('office', 'Office'), ('shop', 'Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='security',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='shop_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sublet_member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
