# Generated by Django 4.2.6 on 2023-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_property_created_at_property_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='fire_extinction',
        ),
        migrations.AddField(
            model_name='property',
            name='fire',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='bachelor_seats',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('0 to 10', '0 to 10'), ('11 to 20', '11 to 20'), ('20 up', '20 up')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='cctv',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='desc',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='electricity',
            field=models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='family_member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='flat_size',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Supply Gas', 'Supply Gas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='generator',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hostel_plan',
            field=models.FileField(blank=True, null=True, upload_to='floor_plan'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hostel_quality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hostel_seats',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lift',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_for',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='office_seats',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Apartment', 'Apartment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(choices=[('family', 'family'), ('sublet', 'sublet'), ('bachelor', 'bachelor'), ('hostel', 'hostel'), ('office', 'office'), ('shop', 'shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='security',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='service_charge',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='shop_quality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sublet_member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
