# Generated by Django 4.2.6 on 2023-11-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_property_fire_extinction_property_fire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('1', '0 to 10'), ('2', '11 to 20'), ('3', '20 up')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_for',
            field=models.CharField(choices=[('1', 'Rent'), ('2', 'Sale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('1', 'Owner'), ('2', 'Apartment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(choices=[('family', 'Family'), ('sublet', 'Sublet'), ('bachelor', 'Bachelor'), ('hostel', 'Hostel'), ('office', 'Office'), ('shop', 'Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='service_charge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
