# Generated by Django 4.2.6 on 2023-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_property_building_age_alter_property_offer_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('1', '0 to 10'), ('2', '11 to 20'), ('3', '20 up')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='electricity',
            field=models.CharField(choices=[('1', 'Prepaid'), ('2', 'Postpaid')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas',
            field=models.CharField(choices=[('1', 'LPG'), ('2', 'Supply Gas')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_for',
            field=models.CharField(choices=[('1', 'Rent'), ('2', 'Sale')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('1', 'Owner'), ('2', 'Apartment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(choices=[('1', 'Family'), ('sublet', 'Sublet'), ('bachelor', 'Bachelor'), ('hostel', 'Hostel'), ('office', 'Office'), ('shop', 'Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='wash',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
