# Generated by Django 4.2.6 on 2023-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_property_balcony_alter_property_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='fire',
        ),
        migrations.AddField(
            model_name='property',
            name='fire_extinguisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False),
        ),
    ]
