# Generated by Django 4.2.6 on 2023-11-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_property_fire_property_fire_extinguisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='fire_extinguisher',
            new_name='fire',
        ),
    ]
