# Generated by Django 4.2.6 on 2023-11-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rename_fire_extinguisher_property_fire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(choices=[('1', 'Family'), ('2', 'Sublet'), ('3', 'Bachelor'), ('4', 'Hostel'), ('5', 'Office'), ('6', 'Shop')], max_length=10),
        ),
    ]
