# Generated by Django 4.2.6 on 2023-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_property_radiocheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(blank=True, choices=[('1', 'Family'), ('2', 'Sublet'), ('3', 'Bachelor'), ('4', 'Hostel'), ('5', 'Office'), ('6', 'Shop')], max_length=10, null=True),
        ),
    ]
