# Generated by Django 4.2.6 on 2023-11-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='offer_for',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=4),
        ),
    ]
