# Generated by Django 4.2.6 on 2023-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_property_offer_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('0 to 10', '0 to 10'), ('11 to 20', '11 to 20'), ('20 up', '20 up')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='electricity',
            field=models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Supply Gas', 'Supply Gas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_for',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Apartment', 'Apartment')], max_length=10),
        ),
    ]
