# Generated by Django 4.2.6 on 2023-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_property_building_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='radiocheck',
            field=models.CharField(blank=True, choices=[('Family', 'Family'), ('Sublet', 'Sublet'), ('Bachelor', 'Bachelor'), ('Hostel', 'Hostel'), ('Office', 'Office'), ('Shop', 'Shop')], max_length=10, null=True),
        ),
    ]
