# Generated by Django 4.2.6 on 2023-11-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_rename_radiocheck_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='radiocheck',
        ),
    ]
