# Generated by Django 4.2.6 on 2023-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_rename_name_property_radiocheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('1', 'Lost Luggages'), ('2', 'Lost Tickets'), ('3', 'Lost Profile')], max_length=1)),
                ('department', models.CharField(choices=[('1', 'Baggage & Luggages'), ('2', 'Support Tickets'), ('3', 'Baggage & Luggages')], max_length=1)),
                ('priority', models.CharField(choices=[('1', 'Normal'), ('2', 'Medium'), ('3', 'Difficult')], max_length=1)),
                ('message', models.TextField()),
            ],
        ),
    ]
