# Generated by Django 4.2.6 on 2023-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='desc',
            field=models.TextField(),
        ),
    ]
