# Generated by Django 4.2.6 on 2023-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_property_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='desc',
            field=models.TextField(max_length=60),
        ),
    ]
