# Generated by Django 4.2.6 on 2023-11-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_propertyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
