# Generated by Django 4.2.6 on 2023-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_delete_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Management',
        ),
    ]
