# Generated by Django 4.2.6 on 2023-11-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_about_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asked_Questions_Form',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
