# Generated by Django 4.2.6 on 2023-11-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_newsletter_delete_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
    ]
