# Generated by Django 4.2.6 on 2023-11-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_alter_property_balcony'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiocheck', models.CharField(blank=True, choices=[('Family', 'Family'), ('Sublet', 'Sublet'), ('Bachelor', 'Bachelor'), ('Hostel', 'Hostel'), ('Office', 'Office'), ('Shop', 'Shop')], max_length=10, null=True)),
                ('property_title', models.CharField(max_length=60)),
                ('floor_number', models.CharField(max_length=60)),
                ('flat_size', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=10)),
                ('service_charge', models.CharField(blank=True, max_length=10, null=True)),
                ('offer_for', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=10)),
                ('property_type', models.CharField(choices=[('Owner', 'Owner'), ('Apartment', 'Apartment')], max_length=10)),
                ('building_age', models.CharField(choices=[('0 to 10', '0 to 10'), ('11 to 20', '11 to 20'), ('20 up', '20 up')], max_length=10)),
                ('bed', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('wash', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('balcony', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True)),
                ('gas', models.CharField(choices=[('LPG', 'LPG'), ('Supply Gas', 'Supply Gas')], max_length=10)),
                ('electricity', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=10)),
                ('security', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('fire', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='latest_news/')),
                ('desc', models.TextField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.division')),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.upazila')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='latest_news_images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.latestnews')),
            ],
            options={
                'verbose_name': 'LatestNews Images',
            },
        ),
    ]
