# Generated by Django 4.2.6 on 2023-11-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_latestnews_latestnewsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='latest_news/'),
        ),
    ]
