# Generated by Django 4.2.6 on 2023-11-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_alter_latestnews_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Management',
        ),
    ]
