# Generated by Django 4.2.6 on 2023-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_managementteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='balcony',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='bed',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='wash',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
